package cdksopssecrets

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsssm"
)

type SopsStringParameterProps struct {
	// The encryption key used by the CDK default Asset S3 Bucket.
	// Default: - Trying to get the key using the CDK Bootstrap context.
	//
	AssetEncryptionKey awskms.IKey `field:"optional" json:"assetEncryptionKey" yaml:"assetEncryptionKey"`
	// Should this construct automatically create IAM permissions?
	// Default: true.
	//
	AutoGenerateIamPermissions *bool `field:"optional" json:"autoGenerateIamPermissions" yaml:"autoGenerateIamPermissions"`
	// The age key that should be used for encryption.
	SopsAgeKey awscdk.SecretValue `field:"optional" json:"sopsAgeKey" yaml:"sopsAgeKey"`
	// The format of the sops file.
	// Default: - The fileformat will be derived from the file ending.
	//
	SopsFileFormat *string `field:"optional" json:"sopsFileFormat" yaml:"sopsFileFormat"`
	// The filepath to the sops file.
	SopsFilePath *string `field:"optional" json:"sopsFilePath" yaml:"sopsFilePath"`
	// The kmsKey used to encrypt the sops file.
	//
	// Encrypt permissions
	// will be granted to the custom resource provider.
	// Default: - The key will be derived from the sops file.
	//
	SopsKmsKey *[]awskms.IKey `field:"optional" json:"sopsKmsKey" yaml:"sopsKmsKey"`
	// The custom resource provider to use.
	//
	// If you don't specify any, a new
	// provider will be created - or if already exists within this stack - reused.
	// Default: - A new singleton provider will be created.
	//
	SopsProvider SopsSyncProvider `field:"optional" json:"sopsProvider" yaml:"sopsProvider"`
	// If you want to pass the sops file via s3, you can specify the bucket you can use cfn parameter here Both, sopsS3Bucket and sopsS3Key have to be specified.
	SopsS3Bucket *string `field:"optional" json:"sopsS3Bucket" yaml:"sopsS3Bucket"`
	// If you want to pass the sops file via s3, you can specify the key inside the bucket you can use cfn parameter here Both, sopsS3Bucket and sopsS3Key have to be specified.
	SopsS3Key *string `field:"optional" json:"sopsS3Key" yaml:"sopsS3Key"`
	// How should the secret be passed to the CustomResource?
	// Default: INLINE.
	//
	UploadType UploadType `field:"optional" json:"uploadType" yaml:"uploadType"`
	// The customer-managed encryption key to use for encrypting the secret value.
	// Default: - A default KMS key for the account and region is used.
	//
	EncryptionKey awskms.IKey `field:"required" json:"encryptionKey" yaml:"encryptionKey"`
	// Information about the parameter that you want to add to the system.
	// Default: none.
	//
	Description *string `field:"optional" json:"description" yaml:"description"`
	// The tier of the string parameter.
	// Default: - undefined.
	//
	Tier awsssm.ParameterTier `field:"optional" json:"tier" yaml:"tier"`
	// The name of the parameter.
	// Default: - a name will be generated by CloudFormation.
	//
	ParameterName *string `field:"optional" json:"parameterName" yaml:"parameterName"`
}

