package cdksopssecrets

import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awskms"
	"github.com/aws/aws-cdk-go/awscdk/v2/awssecretsmanager"
)

// The configuration options of the SopsSecret.
type SopsSecretProps struct {
	// The encryption key used by the CDK default Asset S3 Bucket.
	// Default: - Trying to get the key using the CDK Bootstrap context.
	//
	AssetEncryptionKey awskms.IKey `field:"optional" json:"assetEncryptionKey" yaml:"assetEncryptionKey"`
	// Should this construct automatically create IAM permissions?
	// Default: true.
	//
	AutoGenerateIamPermissions *bool `field:"optional" json:"autoGenerateIamPermissions" yaml:"autoGenerateIamPermissions"`
	// The age key that should be used for encryption.
	SopsAgeKey awscdk.SecretValue `field:"optional" json:"sopsAgeKey" yaml:"sopsAgeKey"`
	// The format of the sops file.
	// Default: - The fileformat will be derived from the file ending.
	//
	SopsFileFormat *string `field:"optional" json:"sopsFileFormat" yaml:"sopsFileFormat"`
	// The filepath to the sops file.
	SopsFilePath *string `field:"optional" json:"sopsFilePath" yaml:"sopsFilePath"`
	// The kmsKey used to encrypt the sops file.
	//
	// Encrypt permissions
	// will be granted to the custom resource provider.
	// Default: - The key will be derived from the sops file.
	//
	SopsKmsKey *[]awskms.IKey `field:"optional" json:"sopsKmsKey" yaml:"sopsKmsKey"`
	// The custom resource provider to use.
	//
	// If you don't specify any, a new
	// provider will be created - or if already exists within this stack - reused.
	// Default: - A new singleton provider will be created.
	//
	SopsProvider SopsSyncProvider `field:"optional" json:"sopsProvider" yaml:"sopsProvider"`
	// If you want to pass the sops file via s3, you can specify the bucket you can use cfn parameter here Both, sopsS3Bucket and sopsS3Key have to be specified.
	SopsS3Bucket *string `field:"optional" json:"sopsS3Bucket" yaml:"sopsS3Bucket"`
	// If you want to pass the sops file via s3, you can specify the key inside the bucket you can use cfn parameter here Both, sopsS3Bucket and sopsS3Key have to be specified.
	SopsS3Key *string `field:"optional" json:"sopsS3Key" yaml:"sopsS3Key"`
	// How should the secret be passed to the CustomResource?
	// Default: INLINE.
	//
	UploadType UploadType `field:"optional" json:"uploadType" yaml:"uploadType"`
	// An optional, human-friendly description of the secret.
	// Default: - No description.
	//
	Description *string `field:"optional" json:"description" yaml:"description"`
	// The customer-managed encryption key to use for encrypting the secret value.
	// Default: - A default KMS key for the account and region is used.
	//
	EncryptionKey awskms.IKey `field:"optional" json:"encryptionKey" yaml:"encryptionKey"`
	// Configure expiration notifications for secret keys.
	//
	// When `enabled: true`, CDK reads unencrypted expiration keys from the local
	// `sopsFilePath` and synthesizes one-time EventBridge Scheduler schedules
	// that publish to SNS before each expiration.
	// Default: - Expiration notifications are disabled.
	//
	ExpirationNotification *ExpirationOptions `field:"optional" json:"expirationNotification" yaml:"expirationNotification"`
	// Should the secret parsed and transformed to json?
	// Default: - undefined - STRING for binary secrets, else no raw output.
	//
	RawOutput RawOutput `field:"optional" json:"rawOutput" yaml:"rawOutput"`
	// Policy to apply when the secret is removed from this stack.
	// Default: - Not set.
	//
	RemovalPolicy awscdk.RemovalPolicy `field:"optional" json:"removalPolicy" yaml:"removalPolicy"`
	// A list of regions where to replicate this secret.
	// Default: - Secret is not replicated.
	//
	ReplicaRegions *[]*awssecretsmanager.ReplicaRegion `field:"optional" json:"replicaRegions" yaml:"replicaRegions"`
	// A name for the secret.
	//
	// Note that deleting secrets from SecretsManager does not happen immediately, but after a 7 to
	// 30 days blackout period. During that period, it is not possible to create another secret that shares the same name.
	// Default: - A name is generated by CloudFormation.
	//
	SecretName *string `field:"optional" json:"secretName" yaml:"secretName"`
}

